apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000  # Specify a NodePort within the range 30000-32767
  - port: 50000
    targetPort: 50000
    nodePort: 30001

